export enum DeviceType {
  BIO_UNIVERSAL = 'BIO_UNIVERSAL',
  SMART_SOCKET = 'SMART_SOCKET',
  NONE = 'NONE',
  TEHNIX = 'TEHNIX',
  BIO_UNIVERSAL_OVEN = 'BIO_UNIVERSAL_OVEN',
  PELLET_LEVEL = 'PELLET_LEVEL'
}
